apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tor-dice
resources:
  - namespace.yaml
  - harbor-pull-secret.yaml
  - deployment.yaml
  - service.yaml
  - image-updater-rbac.yaml
images:
  - name: harbor.sirddail.net/ai/tor-dice
    newTag: 0.0.2
